CANCER DETECTION

In [1]:
import sklearn
from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()

In [4]:
label_names=data['target_names']
labels=data['target']
feature_names=data['feature_names']
features=data['data']

print(label_names)
print(labels)
print(feature_names)
print(features)

['malignant' 'benign']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1

In [8]:
# data into trasining and test set
from sklearn.model_selection import train_test_split
train,test,train_labels,test_labels=train_test_split(features,labels,test_size=0.40,random_state=42)

In [11]:
# Build the Model  Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
model=gnb.fit(train,train_labels)

In [12]:
print(model)

GaussianNB(priors=None)


In [39]:
#Evaluate Model Accuracy by making prediction on test data
preds=gnb.predict(test)
print(preds)
print(test_labels)
from sklearn.metrics import accuracy_score
print(accuracy_score(preds,test_labels))
print("accuracy is ",gnb.score(test, test_labels))

[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 1 0 0 0 1 1 1 0 0 1 1 0 1 0 0 1 1 0 0 0 1 1 1 0 1 1 0 0 1 0 1 1 0 1 0 0
 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0
 0 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1
 0 0 1 1 0 1]
[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 0 1 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 1 0 1 0 1 1 1 0 1 1 1 0 1 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 1 0 1 0 0
 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0
 0 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1
 0 0 1 1 0 1]
0.9517543859649122
accuracy is  0.9517543859649122


In [24]:
help( accuracy_score)

Help on function accuracy_score in module sklearn.metrics.classification:

accuracy_score(y_true, y_pred, normalize=True, sample_weight=None)
    Accuracy classification score.
    
    In multilabel classification, this function computes subset accuracy:
    the set of labels predicted for a sample must *exactly* match the
    corresponding set of labels in y_true.
    
    Read more in the :ref:`User Guide <accuracy_score>`.
    
    Parameters
    ----------
    y_true : 1d array-like, or label indicator array / sparse matrix
        Ground truth (correct) labels.
    
    y_pred : 1d array-like, or label indicator array / sparse matrix
        Predicted labels, as returned by a classifier.
    
    normalize : bool, optional (default=True)
        If ``False``, return the number of correctly classified samples.
        Otherwise, return the fraction of correctly classified samples.
    
    sample_weight : array-like of shape = [n_samples], optional
        Sample weights.
    
   

In [22]:
help( train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, **options)
    Split arrays or matrices into random train and test subsets
    
    Quick utility that wraps input validation and
    ``next(ShuffleSplit().split(X, y))`` and application to input data
    into a single call for splitting (and optionally subsampling) data in a
    oneliner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float, int, None, optional
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to the
        complement of the train size. By default, the value is set 

In [34]:
m=model.predict(test)

In [27]:
g=gnb.predict(test)

In [28]:
g

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1])

In [35]:
from sklearn.model_selection import train_test_split
train,test,train_labels,test_labels=train_test_split(features,labels,test_size=0.40,random_state=42)

In [91]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(train, train_labels)
preds_lr=logreg.predict(test)
print('Accuracy of Logistic regression classifier on training set: {:.2f}'
     .format(logreg.score(train, train_labels)))
print('Accuracy of Logistic regression classifier on test set: {:.2f}'
     .format(logreg.score(test, test_labels)))
print(accuracy_score(preds_lr,test_labels))
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_labels, preds_lr))
print(classification_report(test_labels, preds_lr))

Accuracy of Logistic regression classifier on training set: 0.95
Accuracy of Logistic regression classifier on test set: 0.96
0.9649122807017544
[[ 76   4]
 [  4 144]]
             precision    recall  f1-score   support

          0       0.95      0.95      0.95        80
          1       0.97      0.97      0.97       148

avg / total       0.96      0.96      0.96       228



In [90]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
clf.fit(train, train_labels)
preds_dt=clf.predict(test)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(train, train_labels)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(test, test_labels)))
print(accuracy_score(preds_dt,test_labels))
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_labels, preds_dt))
print(classification_report(test_labels, preds_dt))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 0.93
0.9298245614035088
[[ 73   7]
 [  9 139]]
             precision    recall  f1-score   support

          0       0.89      0.91      0.90        80
          1       0.95      0.94      0.95       148

avg / total       0.93      0.93      0.93       228



In [87]:
clf2 = DecisionTreeClassifier(max_depth=3).fit(train, train_labels)
preds_dt2=clf2.predict(test)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf2.score(train, train_labels)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf2.score(test, test_labels)))
print(accuracy_score(preds_dt2,test_labels))
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_labels, preds_dt2))
print(classification_report(test_labels, preds_dt2))

Accuracy of Decision Tree classifier on training set: 0.97
Accuracy of Decision Tree classifier on test set: 0.94
0.9429824561403509
[[ 75   5]
 [  8 140]]
             precision    recall  f1-score   support

          0       0.90      0.94      0.92        80
          1       0.97      0.95      0.96       148

avg / total       0.94      0.94      0.94       228



In [85]:
#K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(train, train_labels)
preds_kn=knn.predict(test)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(train, train_labels)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(test, test_labels)))
print(accuracy_score(preds_kn,test_labels))
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_labels, preds_kn))
print(classification_report(test_labels, preds_kn))

Accuracy of K-NN classifier on training set: 0.91
Accuracy of K-NN classifier on test set: 0.96
0.956140350877193
[[ 75   5]
 [  5 143]]
             precision    recall  f1-score   support

          0       0.94      0.94      0.94        80
          1       0.97      0.97      0.97       148

avg / total       0.96      0.96      0.96       228



In [53]:
#Linear Discriminant Analysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis()
lda.fit(train, train_labels)
preds_lda=lda.predict(test)
print('Accuracy of LDA classifier on training set: {:.2f}'
     .format(lda.score(train, train_labels)))
print('Accuracy of LDA classifier on test set: {:.2f}'
     .format(lda.score(test, test_labels)))
print(accuracy_score(preds_lda,test_labels))

Accuracy of LDA classifier on training set: 0.97
Accuracy of LDA classifier on test set: 0.96
0.9605263157894737


In [84]:
#Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(train, train_labels)
preds_gn=gnb.predict(test)
print('Accuracy of GNB classifier on training set: {:.2f}'
     .format(gnb.score(train, train_labels)))
print('Accuracy of GNB classifier on test set: {:.2f}'
     .format(gnb.score(test, test_labels)))
print(accuracy_score(preds_gn,test_labels))
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_labels, preds_gn))
print(classification_report(test_labels, preds_gn))

Accuracy of GNB classifier on training set: 0.94
Accuracy of GNB classifier on test set: 0.95
0.9517543859649122
[[ 73   7]
 [  4 144]]
             precision    recall  f1-score   support

          0       0.95      0.91      0.93        80
          1       0.95      0.97      0.96       148

avg / total       0.95      0.95      0.95       228



In [83]:
#Support Vector Machine
from sklearn.svm import SVC

svm = SVC()
svm.fit(train, train_labels)
#preds_svm=svm.probability(test)
preds_svm=svm.predict(test)
print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(svm.score(train, train_labels)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(svm.score(test, test_labels)))
print(accuracy_score(preds_svm,test_labels))
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
#pred = knn.predict(test)
#print(confusion_matrix(test, preds_svm))
#print(classification_report(test, pred_svm))
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_labels, preds_svm))
print(classification_report(test_labels, preds_svm))

Accuracy of SVM classifier on training set: 1.00
Accuracy of SVM classifier on test set: 0.65
0.6491228070175439
[[  0  80]
 [  0 148]]
             precision    recall  f1-score   support

          0       0.00      0.00      0.00        80
          1       0.65      1.00      0.79       148

avg / total       0.42      0.65      0.51       228



C:\Users\abc\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [66]:
#The KNN algorithm was the most accurate model that we tried. The confusion matrix provides an indication of one error made.

#Finally, the classification report provides a breakdown of each class by precision, recall, f1-score and support showing excellent results (However, the test set was small).
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
pred = knn.predict(test)
print(confusion_matrix(test, pred))
print(classification_report(test, pred))


ValueError: Classification metrics can't handle a mix of continuous-multioutput and binary targets

In [74]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
pred = knn.predict(test)
print(confusion_matrix(test, pred))
#print(classification_report(test, pred))

ValueError: Classification metrics can't handle a mix of continuous-multioutput and binary targets

In [75]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(train, train_labels)
preds_kn=knn.predict(test)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(train, train_labels)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(test, test_labels)))
print(accuracy_score(preds_kn,test_labels))

Accuracy of K-NN classifier on training set: 0.91
Accuracy of K-NN classifier on test set: 0.96
0.956140350877193


In [82]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_labels, preds_kn))
print(classification_report(test_labels, preds_kn))

[[ 75   5]
 [  5 143]]
             precision    recall  f1-score   support

          0       0.94      0.94      0.94        80
          1       0.97      0.97      0.97       148

avg / total       0.96      0.96      0.96       228

